name: Build iOS App

on:
  push:
    branches:
      - main  # تشغيل عند رفع كود إلى الفرع الرئيسي

jobs:
  build:
    runs-on: macos-latest  # تشغيل على سيرفر macOS في GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # تحميل الكود من المستودع

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # استخدم نسخة Flutter التي لديك

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Upload iOS Build Artifact
	uses: actions/upload-artifact@v4
 	with:
    	  name: ios-build
    	  path: build/ios/iphoneos

